### ISSUE TITLE
Usernames are not escaped (in tip notification)

### ISSUE THREAD

**Issue by justdmitry** [bbedward/Graham_Nano_Tip_Bot#24]
Here is notification screenshot:

![sample](https://user-images.githubusercontent.com/3540597/43652948-508325b8-974f-11e8-97f7-e4eb663df64a.png)

It seems that user have `'` in his name, which had not been encoded, and Discord received it as formatting char. Not sure how powerful is message formatting in Discord and what negative result can "smart" username lead to, but this is still kind of injection bug.

**Comment by renesq** [comment]
i feel like this could be prevented by using the `<@397868283870707713>` technique. Discord will automatically make it `@renesq` then

**Comment by bbedward** [comment]
Addressed this in v4

https://github.com/bbedward/Graham_Nano_Tip_Bot/tree/v4?files=1
