### ISSUE TITLE
Add support for graphene based coins like STEEM and BTS

### ISSUE THREAD

**Issue by AneilPatel05** [bbedward/Graham_Nano_Tip_Bot#31]
Hello,
Great work indeed. I appreciate the hard work done by you. I am looking for similar tip bot with STEEM coins since steem has large userbase on discord. I can help with the configuration of steem nodes and address creation. Might create a PR if you agree.

PS : did you know you can be rewarded by utopian.io for your open source work with STEEM ? Check out https://www.utopian.io and https://steemit.com/@utopian-io.
You can create a steem account for as low as $2.50 at https://www.swapsteem.online

**Comment by bbedward** [comment]
Not in the scope of this project, closing.
