### ISSUE TITLE
QOL Improve Copy and Pasting of address from .wfu command

### ISSUE THREAD

**Issue by Kirby1997** [bbedward/Graham_Nano_Tip_Bot#33]
https://github.com/bbedward/Graham_Nano_Tip_Bot/blob/master/bot.py#L1962

Instead of separating items {2} and {3} with a space I feel like they should be separated by a new line. Unless the Discord window is very large, these items are not displayed on the same line usually. This results in it being too easy to copy the space that follows the address as it is very small and hard to notice. This can be annoying when trying to copy and paste the address and forgetting.

![annoying space](https://user-images.githubusercontent.com/13118604/60274099-5f00bb80-98ef-11e9-89e1-977c7abd357b.png)

**Comment by bbedward** [comment]
Done in v4

https://github.com/bbedward/Graham_Nano_Tip_Bot/tree/v4
