### ISSUE TITLE
Reformat code to be PEP-8 Compliant.

### ISSUE THREAD

**Issue by metaperl** [bbedward/Graham_Nano_Tip_Bot#6]
Hello, I noticed this is your first code in Python and Discord. It is very impressive. I don't know how you feel about this, but the standard coding guidelines for Python are outlined in [PEP-8](https://www.python.org/dev/peps/pep-0008/). 

I was successful in reformatting the code automatically using [autopep8](https://github.com/hhatto/autopep8) and this command line:

    autopep8 --in-place --aggressive --aggressive

And then changing to the `util` directory and doing the same.

**Comment by bbedward** [comment]
Thank you for the suggestion I will certainly look into this
