### ISSUE TITLE
Single codebase for banano/nano

### ISSUE THREAD

**Issue by bbedward** [bbedward/Graham_Nano_Tip_Bot#7]
There's really no need for two separate codebases.

We can just add a setting for banano, then for banano we use different raw conversions and aliases, block explorers, etc

The arrest/mute type of functionality should be moved to Beatrice

**Comment by metaperl** [comment]
Before you integrate the two, I would suggest that you use some basic object-oriented programming to encapsulate related things in a single class.

E.g., some aspects of a command are defined in one place and other parts of the same command are defined in another.  For example, we see [certain aspects of the BALANCE command defined beginning at Line 80](https://github.com/bbedward/Graham_Nano_Tip_Bot/blob/master/bot.py#L80). The response text for that came command is defined [200 lines later](https://github.com/bbedward/Graham_Nano_Tip_Bot/blob/master/bot.py#L386).
