### ISSUE TITLE
Get Bot Able To Run On Mutliple Servers

### ISSUE THREAD

**Issue by Computer-Genuis** [bbedward/Graham_Nano_Tip_Bot#9]

**Comment by bbedward** [comment]
#3 and #4 are the main pre-requisites for this.

#4 is already partially implemented but there's more that could be done as far as work generate

**Comment by bbedward** [comment]
Done in rewrite

https://github.com/bbedward/Graham_Nano_Tip_Bot/tree/v4?files=1
